sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20040922xby
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPxUWWpV4CitqVtAskC
    access-key-secret: AIbqbdnfEqViqoV5GFKNfpoWHuEgCk
    bucket-name: skt-shangli
